version: '3.8'
services:
  app:
    build: .
    container_name: topyonsis_app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - tpy-network
  webserver:
    image: nginx:stable
    container_name: topyonsis_nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - tpy-network
  mysql:
    image: mysql:8.0
    container_name: topyonsis_mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: topyonsis
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - tpy-network
  redis:
    image: redis:7
    container_name: topyonsis_redis
    ports:
      - "6379:6379"
    networks:
      - tpy-network

volumes:
  dbdata:

networks:
  tpy-network:
    driver: bridge
